# Nombre de la aplicación
spring.application.name=predictmaint-backend

# H2 - Base de datos en memoria
spring.datasource.url=jdbc:h2:mem:predictmaintdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 — para ver los datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

# Cargar data.sql al iniciar
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Puerto del servidor
server.port=8080
